name: Build Executables for Windows, Linux, and macOS

on:
  workflow_dispatch:  # Permite executar manualmente

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller matplotlib

      - name: Build executable
        run: pyinstaller --onefile SimulEscal.py

      - name: Rename executable for clarity
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv dist/SimulEscal.exe dist/SimulEscal-windows.exe
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mv dist/SimulEscal dist/SimulEscal-linux
          else
            mv dist/SimulEscal dist/SimulEscal-macos
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimulEscal-${{ matrix.os }}
          path: dist/
