name: Build Linux Executable

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller matplotlib
      - run: pyinstaller --onefile SimulEscal.py
      - uses: actions/upload-artifact@v4
        with:
          name: simulador-linux
          path: dist/
